#!/usr/bin/env bash
# configures Nginx so that /redirect_me redirects to another page
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://youtu.be/WPkMUU9tUqk permanent;" /etc/nginx/sites-available/default

sudo service nginx start
