#!/usr/bin/env bash
# install and configure HAproxy on load balancer server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo "
    backend web-backend
        balance roundrobin
        server 1451-web-01 104.196.113.125:80 check
        server 1451-web-02 54.145.19.201:80 check

    frontend http
        bind *:80
        mode http
        default_backend web-backend" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
