#!/usr/bin/env bash
#displays numbers from 1 to 20
#displays bad luck from China after the 4th iteration
#displays bad luck from Japan after the 9th loop iteration
#displays bad luck from Italy after the 17th loop iteration
i=1
while [ $i -le 20 ] ; do
	case $i in
	4)
		echo $i
		echo "bad luck from China"
		;;
	9)
		echo $i
		echo "bad luck from Japan"
		;;
	17)
		echo $i
		echo "bad luck from Italy"
		;;
	*)
		echo $i
		;;
	esac
	((i++))
done
